# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A nossa Convenção Nacional 2026'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    align: 'center'
    fixed_to_top: true
    logo:
      text: 'XXXII CPNA 2026'
      # Logo filename in `assets/media/` folder
#      filename: 'logo.svg'
    button:
      enable: true
      text: 'Registos (em breve)'
      url: '#registos'
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: '© {year} XXXII CPNA'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
